---
- name: Ensure service group
  become: true
  tags: ['service-user']
  ansible.builtin.group:
    name: "{{ service_user_group_name }}"
    gid: "{{ service_user_group_id|default(omit, true) }}"

- name: Ensure service user
  become: true
  tags: ['service-user']
  ansible.builtin.user:
    name: "{{ service_user_name }}"
    group: "{{ service_user_group_name }}"
    uid: "{{ service_user_id|default(omit, true) }}"
    groups: "{{ service_user_additional_groups }}"
    append: true

- name: Ensure additional user service group membership
  become: true
  loop: "{{ service_user_additional_group_members }}"
  tags: ['service-user']
  ansible.builtin.user:
    name: "{{ item }}"
    append: true
    groups: ["{{ service_user_group_name }}"]

- name: Ensure additional user extended group membership
  when: service_user_extended_group_membership|bool
  become: true
  loop: "{{ service_user_additional_group_members }}"
  tags: ['service-user']
  ansible.builtin.user:
    name: "{{ item }}"
    append: true
    groups: "{{ service_user_additional_groups }}"
